### ISSUE TITLE
tracker for initial release

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#15]
Docs
- [x] Documentation website generated
- [x] Documentation website guides ready
- [x] Documentation website tutorials ready for each platform
- [x] Documentation reference
- [x] Crates are sufficiently documented 
- [x] Examples are ready and clean

Technical
- [x] Listeners actually drop their contents
- [x] Event delegator for webview and mobile
- [x] Controlled components work as advertised
- [x] HTML macro works as advertised
- [x] "Garbage collection" phase (dropping outdated elements, clearing listeners, remove/replace)
- [x] Keys work as advertised in elements/components
- [x] The powerful keyed diffing approach is finally included again
- [x] Safety of core mechanisms is closely evaluated again
- [x] use_task and immediate task system are re-evaluated
- [x] Heuristics engine
- [x] pause-able cooperative scheduler
- [x] rehydration implemented properly
- [x] ~~basic const/static generated~~ this will be part of the "templates" update

Ecosystem
- [x] A router
- [x] A cross-platform codeblock system 
- [ ] Studio/CLI is given better error messages and a proper live-reloading system (with local sockets and stuff)
- [ ] extension is officially released (blocked by studio)
- [x] ~~assets crate gets some basic functionality/sketches~~ punting until later

Release
- [x] Official releases cut for all major crates
- [x] Social Media posts

Blockers
- [x] event bubbling
- [x]  ~~effects exposed to mutations~~ effects are now just tasks but handled through the use_effect hook in hooks
- [x] ~~noderefs exposed to mutations~~ might punt node refs into the next update
- [x] hard allocations for props
- [x] miri says we leak memory
- [x] more guards/safety/debug assertions
- [x] more tests
- [x] resolve nodelinks as children
- [ ] Suspense
- [x] Tasks
- [x] docs
- [x] site
- [x] router

**Comment by jkelleyrtp** [comment]
Final tweaks:
- [*] use_state can be simplified to just return the `&mut `
- [*] curly braces can be removed inline

**Comment by jkelleyrtp** [comment]
Closing since we've already released - but good stuff here :)
