### ISSUE TITLE
Tracking: Development Iteration Time

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/dioxus#2426]
**Description**
This is a tracking issue for improving development iteration times for Dioxus, with a general focus on the component library.

**Tracked Issues**
These first three combined would be the best speed up. It would allow hot reloading with manganis in workspaces. However, it depends on if workspace hot reloading is included with the second one.
1. [x] https://github.com/DioxusLabs/collect-assets/issues/23
2. [x] https://github.com/DioxusLabs/dioxus/pull/2258 
3. [x] #2429
- [ ] https://github.com/DioxusLabs/dioxus/issues/2425
- [x] https://github.com/DioxusLabs/collect-assets/issues/29
- [x] https://github.com/DioxusLabs/collect-assets/issues/20
- [x] https://github.com/DioxusLabs/collect-assets/issues/14
- [x] https://github.com/DioxusLabs/dioxus/pull/2421

**Comment by jkelleyrtp** [comment]
Now that there's only the SCSS issue left, I'm going to close this.
