### ISSUE TITLE
Megathread: cli 0.6.0-alpha quirks/issues/ux/perf

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#2788]
**Problem**

We have a number of quirks / bugs in the CLI post-rewrite that need to be resolved before releasing to the general public.

This issue is where we put them.

- [x] Fullstack server takes a moment to start leading to the default-router's "connection refused" screen
- [x] The tui sidebar makes it impossible to copy logs - needs to be moved to a row #2846
- [x] The tui scrolling is just janky/slow/hacky *Improved* in #2846
- [x] The tui "modal" is not complete at all and needs more helpful info (summary of config, urls for dev server, process names, etc)
- [x] Missing logs for downloading/compiling dependency crates
- [x] tracing annotations make it harder for vscode to implement jump-to-file
- [x] Fullstack is just broken due to a port forwarding issue
- [x] Asset collection causes unnecessary recompiles due to thrashing of env vars in build scripts
- [x] CWD for bundle (used by icon search) is just wrong leading to #2344 
- [x] Collecting and optimizing assets should be optional/skipped in dev mode in favor of just copying assets #2844
- [x] wasm-bindgen crashing nukes our TUI
- [x] We don't invalidate literals in hotreloading that are the same as the original, meaning you can hotreload true -> false but not back to true
- [x] We don't send down old hotreloaded templates to new clients anymore
- [ ] We don't properly set cors/CSP/XSRF headers on assets to clients in dev
- [ ] we should print the resolved config on a panic in the cli for better debugging

**Comment by Andrew15-5** [comment]
> - [ ] Fullstack is just broken due to a port forwarding issue

Is this the same as:

- [ ] "Failed to find index.html" Fullstack panic

```
[app] thread 'main' panicked at /cargo/git/checkouts/dioxus-1e619ce595d3799d/bd58a92/packages/fullstack/src/serve_config.rs:91:37:
[app] 2024-08-04T12:04:46.395679Z  WARN dioxus_cli_config: A library is trying to access the crate's configuration, but the dioxus CLI was not used to build the application.
[app] Failed to find index.html. Make sure the index_path is set correctly and the WASM application has been built.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[app] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

?

- [ ] Some messages sometimes are written on top of the UI

![image](https://github.com/user-attachments/assets/fcd6ebf7-4632-40a3-aae5-f95705bef7bc)

**Comment by Andrew15-5** [comment]
I will non-CLI issues here (but they are emerged from `dx serve`):

- [ ] After a successful build, removing any of the `a {}` elements (including the `img` itself) causes the `img`/SVG to disappear without the ability to restore it (only via tab reload).

  ```rs
      rsx! {
          head::Link { rel: "stylesheet", href: asset!("./assets/main.css") }
          img { src: asset!("./assets/header.svg"), id: "header" }
          div { id: "links",
              a { href: "https://dioxuslabs.com/learn/0.5/", "📚 Learn Dioxus" }
              a { href: "https://dioxuslabs.com/awesome", "🚀 Awesome Dioxus" }
              a { href: "https://github.com/dioxus-community/", "📡 Community Libraries" }
              a { href: "https://github.com/DioxusLabs/dioxus-std", "⚙️ Dioxus Standard Library" }
              a { href: "https://marketplace.visualstudio.com/items?itemName=DioxusLabs.dioxus",
                  "💫 VSCode Extension"
              }
              a { href: "https://discord.gg/XgGxMSkvUM", "👋 Community Discord" }
          }
      }
  ```

**Comment by DogeDark** [comment]
Add to the list:

- [ ] Desktop logs aren't outputted in the terminal until the app exits.

**Comment by FragrantArmpit** [comment]
Another thing to discuss: #2857

**Comment by dbcfd** [comment]
> > Fullstack is just broken due to a port forwarding issue
> 
> Is this the same as (I no longer think it's the same issue and I don't have the port forwarding issue):
> 
>     * [x]  "Failed to find index.html" Fullstack panic
>       ```
>       [app] thread 'main' panicked at /cargo/git/checkouts/dioxus-1e619ce595d3799d/bd58a92/packages/fullstack/src/serve_config.rs:91:37:
>       [app] 2024-08-04T12:04:46.395679Z  WARN dioxus_cli_config: A library is trying to access the crate's configuration, but the dioxus CLI was not used to build the application.
>       [app] Failed to find index.html. Make sure the index_path is set correctly and the WASM application has been built.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
>       [app] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>       ```

I have been able to work around this in `0.6.0-alpha.2` by setting `out_dir` to `dist/public`. It looks like https://github.com/DioxusLabs/dioxus-template/pull/44 should be adjusted to use this since https://github.com/DioxusLabs/dioxus/blob/1dfa1b5e7f39b8ccd2e6b18bd9077d05e82d5504/packages/fullstack/src/serve_config.rs#L57 will use `public_path()` if `index_path` is not set.

**Comment by DogeDark** [comment]
@Andrew15-5 I'm not sure if we will still have filtering as the TUI has been redone to be a viewport with println-like logs.

**Comment by Andrew15-5** [comment]
> the TUI has been redone

What? Where? I compiled the latest version a few hours ago. Are you talking about the future that hasn't come yet?

**Comment by jkelleyrtp** [comment]
TUI has been rewritten and there are new bugs of course, but most of these have been solved
